# Generated by Django 6.0.6 on 2026-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Превью изображения'),
        ),
    ]
