# Generated by Django 6.0.6 on 2026-06-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='URL изображения'),
        ),
    ]
