# Generated by Django 6.0.6 on 2026-06-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='image_urls',
        ),
    ]
