# Generated by Django 6.0.6 on 2026-06-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_image_url_project_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_urls',
        ),
    ]
